### ISSUE TITLE
how to generate images of given latex for different fonts for model robustness

### ISSUE THREAD

**Issue by saurabhvyas** [Miffyli/im2latex-dataset#8]
I want to generate images of my maths latex, such that each image is rendered with a different font, so that model is more robustness, How can I do this with the current code ?

Thanks

**Comment by Miffyli** [comment]
You can add new elements to [this dictionary](https://github.com/Miffyli/im2latex-dataset/blob/master/src/formula2image.py#L82) to render same formula in multiple ways.

Key is the name of render setup and value is a list of three elements:
- Skeleton: The LaTeX template where the formula [will be inserted](https://github.com/Miffyli/im2latex-dataset/blob/master/src/formula2image.py#L109)
- Rendering command: The call used to [render the image](https://github.com/Miffyli/im2latex-dataset/blob/master/src/formula2image.py#L125)
- Function to check [if file exists](https://github.com/Miffyli/im2latex-dataset/blob/master/src/formula2image.py#L104) (to be honest, I can not recall why this is needed).

If you need something more complex you need to stab code yourself by e.g. opening the rendered image and adding noise to it manually.

**Comment by saurabhvyas** [comment]
Okay thanks for your response
